export const medicos = [
  {
    id: 1,
    nome: "Dr. João Silva",
    especialidade: "clínico geral",
    psf: "PSF I",
  },
  {
    id: 2,
    nome: "Dra. Maria Oliveira",
    especialidade: "cardiologia",
    psf: "PSF II",
  },
  {
    id: 3,
    nome: "Dr. Pedro Santos",
    especialidade: "pediatria",
    psf: "PSF I",
  },
  {
    id: 4,
    nome: "Dra. Ana Costa",
    especialidade: "ginecologia",
    psf: "PSF III",
  },
  {
    id: 5,
    nome: "Dr. Lucas Almeida",
    especialidade: "ortopedia",
    psf: "PSF II",
  },
  {
    id: 6,
    nome: "Dra. Fernanda Lima",
    especialidade: "dermatologia",
    psf: "PSF III",
  },
  {
    id: 7,
    nome: "Dr. Marcos Pereira",
    especialidade: "neurologia",
    psf: "PSF II",
  },
  {
    id: 8,
    nome: "Dra. Juliana Rocha",
    especialidade: "endocrinologia",
    psf: "PSF I",
  },
  {
    id: 9,
    nome: "Dr. Tiago Martins",
    especialidade: "gastroenterologia",
    psf: "PSF III",
  },
  {
    id: 10,
    nome: "Dra. Cláudia Mendes",
    especialidade: "psiquiatria",
    psf: "PSF IV",
  },
  {
    id: 11,
    nome: "Dr. Felipe Nascimento",
    especialidade: "odontologia",
    psf: "PSF I",
  },
  {
    id: 12,
    nome: "Dra. Renata Souza",
    especialidade: "otorrinolaringologia",
    psf: "PSF II",
  },
  {
    id: 13,
    nome: "Dr. André Lima",
    especialidade: "urologia",
    psf: "PSF III",
  },
  {
    id: 14,
    nome: "Dra. Laura Almeida",
    especialidade: "fisioterapia",
    psf: "PSF I",
  },
  {
    id: 15,
    nome: "Dr. Eduardo Martins",
    especialidade: "anestesiologia",
    psf: "PSF IV",
  },
  {
    id: 16,
    nome: "Dra. Sofia Torres",
    especialidade: "cirurgia geral",
    psf: "PSF II",
  },
  {
    id: 17,
    nome: "Dr. Gabriel Reis",
    especialidade: "reumatologia",
    psf: "PSF III",
  },
  {
    id: 18,
    nome: "Dra. Aline Ferreira",
    especialidade: "pneumologia",
    psf: "PSF II",
  },
  {
    id: 19,
    nome: "Dr. Renato Pires",
    especialidade: "medicina do trabalho",
    psf: "PSF I",
  },
  {
    id: 20,
    nome: "Dra. Vanessa Almeida",
    especialidade: "medicina esportiva",
    psf: "PSF IV",
  },
];
